// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx-kuwjY6Xr5QWlhO9ntUCma6BLbc5TjM',
    appId: '1:969223638649:web:a4954541cfec6369cacea8',
    messagingSenderId: '969223638649',
    projectId: 'tbo-app-3535e',
    authDomain: 'tbo-app-3535e.firebaseapp.com',
    storageBucket: 'tbo-app-3535e.firebasestorage.app',
    measurementId: 'G-XTZ8XS2KRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMxe-U0FdoO7JimFXoNIsO7tnIyanNPLE',
    appId: '1:969223638649:android:907b9ff8034f6f93cacea8',
    messagingSenderId: '969223638649',
    projectId: 'tbo-app-3535e',
    storageBucket: 'tbo-app-3535e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9-j3DhLbt6ez7jerR7eEDqGqvbgGz-e0',
    appId: '1:969223638649:ios:4be9fcb75fd6f7f7cacea8',
    messagingSenderId: '969223638649',
    projectId: 'tbo-app-3535e',
    storageBucket: 'tbo-app-3535e.firebasestorage.app',
    iosBundleId: 'com.example.tboApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9-j3DhLbt6ez7jerR7eEDqGqvbgGz-e0',
    appId: '1:969223638649:ios:4be9fcb75fd6f7f7cacea8',
    messagingSenderId: '969223638649',
    projectId: 'tbo-app-3535e',
    storageBucket: 'tbo-app-3535e.firebasestorage.app',
    iosBundleId: 'com.example.tboApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx-kuwjY6Xr5QWlhO9ntUCma6BLbc5TjM',
    appId: '1:969223638649:web:ec76d07ac4f7dde5cacea8',
    messagingSenderId: '969223638649',
    projectId: 'tbo-app-3535e',
    authDomain: 'tbo-app-3535e.firebaseapp.com',
    storageBucket: 'tbo-app-3535e.firebasestorage.app',
    measurementId: 'G-TGKQPQBEYX',
  );
}
