default_platform(:ios)
 
platform :ios do

  desc "Push a new build to TestFlight"

  lane :deploy_testflight do

    api_key = app_store_connect_api_key(

      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],

      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],

      key_content: ENV["APP_STORE_CONNECT_API_KEY"]

    )
 
    upload_to_testflight(

      api_key: api_key,

      ipa: "../build/ios/ipa/app.ipa",

      skip_waiting_for_build_processing: true,

      skip_submission: true

    )

  end
 
  desc "Deploy directly to App Store"

  lane :deploy_app_store do

    api_key = app_store_connect_api_key(

      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],

      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],

      key_content: ENV["APP_STORE_CONNECT_API_KEY"]

    )
 
    upload_to_app_store(

      api_key: api_key,

      ipa: "../build/ios/ipa/app.ipa",

      submit_for_review: false,

      automatic_release: false,

      skip_metadata: false,

      skip_screenshots: false,

      precheck_include_in_app_purchases: false

    )

  end

end
 