default_platform(:android)
 
platform :android do

  desc "Deploy a new version to the Google Play Store"

  lane :deploy_play_store do

    upload_to_play_store(

      track: 'production',

      aab: '../build/app/outputs/bundle/release/app-release.aab',

      skip_upload_metadata: false,

      skip_upload_images: false,

      skip_upload_screenshots: false,

      release_status: 'completed'

    )

  end
 
  desc "Deploy to internal testing track"

  lane :deploy_internal do

    upload_to_play_store(

      track: 'internal',

      aab: '../build/app/outputs/bundle/release/app-release.aab',

      skip_upload_metadata: true,

      skip_upload_images: true,

      skip_upload_screenshots: true

    )

  end
 
  desc "Deploy to beta testing track"

  lane :deploy_beta do

    upload_to_play_store(

      track: 'beta',

      aab: '../build/app/outputs/bundle/release/app-release.aab',

      skip_upload_metadata: true,

      skip_upload_images: true,

      skip_upload_screenshots: true

    )

  end

end
 